logging_config_path: "ml_project/configs/logging.conf.yaml"
input_data_path: "ml_project/data/raw/heart.csv"
output_model_path: "ml_project/tests/models/model.pkl"
metric_path: "ml_project/tests/models/metrics.json"
splitting_params:
  test_size: 0.3
  random_state: 13
train_params:
  criterion: "gini"
  n_estimators: 100
  max_depth: 10
  random_state: 13
preprocessing_params:
  scaler: 'StandardScaler'
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "target"